### ISSUE TITLE
No permission to access the dataset

### ISSUE THREAD

**Issue by KevinCheung2259** [alpa-projects/mms#103]
I have encountered access restrictions and am unable to download the Microsoft Azure_v1 Trace and Microsoft Azure_v2 Trace datasets from the provided links.

Could you kindly grant me access to these datasets, or guide me through the process of obtaining them? If there are alternative ways to access these datasets, I would greatly appreciate any information you can provide.

Thank you for your contributions to the open-source community, and I look forward to your response !

**Comment by PKUFlyingPig** [comment]
This dataset is public on their [github repo](https://github.com/Azure/AzurePublicDataset/blob/master/AzureFunctionsDataset2019.md)

**Comment by Kevin-Zhang-SYSU** [comment]
Thank you so much! I have also reviewed this repository, but I noticed that the dataset you are using in the code is in .pkl format, which is different from the dataset link you provided. May I ask if you have done any additional processing?

**Comment by KevinCheung2259** [comment]
Well, at first I thought your dataset was processed, but I found the process in your code. Thank you very much!

**Comment by GitHubDiom** [comment]
> Well, at first I thought your dataset was processed, but I found the process in your code. Thank you very much!

How did you obtain the trace in a `.pkl` file? As far as I know, Azure Trace data is typically provided in `.csv` format.

**Comment by KevinCheung2259** [comment]
已收到，谢谢！

**Comment by GitHubDiom** [comment]
> > Well, at first I thought your dataset was processed, but I found the process in your code. Thank you very much!
> 
> How did you obtain the trace in a `.pkl` file? As far as I know, Azure Trace data is typically provided in `.csv` format.

Got it! It seems I’ll need to set it up myself using `./benchmarks/alpa/prepare_trace.py` and add some code like this:
```python
from alpa_serve.trace import preprocess_azure_v2_trace, preprocess_azure_v1_trace

trace_dir = "/path/to/azure2/AzureFunctionsInvocationTraceForTwoWeeksJan2021/"
preprocess_azure_v2_trace(trace_dir)
trace_dir = "/path/to/azure1/azurefunctions-dataset2019/"
preprocess_azure_v1_trace(trace_dir)

```
