### ISSUE TITLE
Combined with batch

### ISSUE THREAD

**Issue by NaphJohn** [alpa-projects/mms#99]
Hello, Lianmin Zheng: 
I would like to ask how the controller works. 
Can the controller be combined with the idea of the batch, for example, if the controller sends ten requests to a group1, can these requests be optimized with the idea of the batch, so that the overall latency is shorter？

**Comment by merrymercy** [comment]
Sure. See our batch policy here https://github.com/alpa-projects/mms/pull/9
cc @PKUFlyingPig

**Comment by NaphJohn** [comment]
Could I add your wechat privately to discuss more skills?

**Comment by PKUFlyingPig** [comment]
May you list your questions here? I will try to answer it.
